spring:
  application:
    name: coffee-machine

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Aleksey1232

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration